version: "3.0"

# http://localhost:9001/ - minio
# http://localhost:15670/ - rabit
# http://localhost:8000/api/v1 - api

services:

  database:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql-core/data/
    env_file:
      - ./docker/.env
    networks:
      - super-app
    ports:
      - "5430:5432"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    image: super-app
    restart: always
#    command: "uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
    command: "python manage.py runserver 0.0.0.0:8000"
    networks:
      - super-app
    env_file:
      - ./docker/.env
    ports:
      - "8000:8000"
    volumes:
      - media:/code/media
      - static:/code/static
      - ./app:/code
    depends_on:
      - redis
      - database
      - rabbit
      - minio
      - createbucket
    extra_hosts:
      - "localhost:172.17.0.1"

  rabbit:
    image: rabbitmq:management-alpine
    hostname: core-rabbit
    restart: always
    networks:
      - super-app
    ports:
      - "15670:15672"
      - "5670:5672"

  redis:
    restart: always
    image: redis:alpine
    hostname: core-redis
    networks:
      - super-app
    ports:
      - "6370:6379"

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    environment:
      - "MINIO_ROOT_USER=user"
      - "MINIO_ROOT_PASSWORD=password"
    command: server /data --console-address :9001
    networks:
      - super-app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  createbucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 user password;
      /usr/bin/mc mb s3/static/;
      /usr/bin/mc anonymous set download s3/static;
      "

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A core worker -c 3 --loglevel=INFO
    networks:
      - super-app
    env_file:
      - ./docker/.env
    volumes:
      - ./app:/code
    depends_on:
      - redis
      - database
      - rabbit
      - minio
      - createbucket

#  nginx:
#    build: ./nginx
#    volumes:
#      - staticfiles:/staticfiles
#    ports:
#      - "80:80"
#    depends_on:
#      - app

volumes:
  postgres_data:
  media:
  static:
  data:

networks:
  super-app:
    driver: bridge
