# Generated by Django 4.1.4 on 2023-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to='images/original/%Y/%m/%d', verbose_name='Оригинальная картина'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/thumbnail/%Y/%m/%d', verbose_name='Thumbnail картина'),
        ),
    ]
