# Generated by Django 4.1.4 on 2023-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/conveniences', verbose_name='Иконки'),
        ),
    ]
