# Generated by Django 4.1.4 on 2023-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.TextField(choices=[('HIGHEST', 'Наивысший приоритет'), ('MEDIUM', 'Средний приоритет'), ('LOW', 'Низкий приоритет')], default='MEDIUM', max_length=50),
        ),
    ]
