# Generated by Django 4.1.4 on 2023-05-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_original_alter_image_thumbnail'),
        ('product', '0003_comment_is_active'),
    ]

    operations = [
    ]
