# Generated by Django 4.1.4 on 2023-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_likes_product_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail/%Y/%m/%d', verbose_name='Оригинальная картина'),
        ),
    ]
