# Generated by Django 4.1.4 on 2023-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_merge_20230513_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
    ]
