# Generated by Django 4.1.4 on 2023-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail/%Y/%m/%d', verbose_name='Сжатая картина'),
        ),
    ]
