# Generated by Django 4.2.6 on 2023-10-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_booking_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
