# Generated by Django 4.1.4 on 2023-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_booking_product_favorites_booking_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Rating'),
        ),
    ]
