# Generated by Django 4.1.4 on 2023-05-31 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ('-created_at',), 'verbose_name': 'Избранные', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AddField(
            model_name='favorites',
            name='like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='product.like'),
            preserve_default=False,
        ),
    ]
