# Generated by Django 4.1.4 on 2023-04-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_image_extension_image_mimetype_image_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='image',
            name='mimetype',
        ),
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
