# Generated by Django 4.1.4 on 2023-06-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_favorites_options_favorites_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='convenience',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('-created_at',)},
        ),
    ]
