# Generated by Django 4.1.4 on 2023-04-20 18:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_image_extension_remove_image_mimetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=10, scale=0.5, size=[324, 300], upload_to='images/thumbnail/%Y/%m/%d'),
        ),
    ]
