# Generated by Django 4.1.4 on 2023-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to='images/original', verbose_name='Оригинальная картина'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/thumbnail', verbose_name='Thumbnail картина'),
        ),
    ]
