# Generated by Django 4.1.4 on 2023-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_image_original_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконки'),
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата Latitude'),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата Longitude'),
        ),
    ]
