# Generated by Django 4.1.4 on 2023-05-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_latitude_product_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
    ]
